In [1]:
## https://numpy.org/
!pip install numpy

In [2]:
import numpy as np
np.__version__

'1.25.2'

In [ ]:
matrixList = [[10,20,30],[10,50,60]]
np.array(matrixList)

array([[10, 20, 30],
       [10, 50, 60]])

In [ ]:
## son eleman dahil değil
## arrange(başlangıç_degeri, bitiş_değeri, step)
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
## son eleman dahil
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [ ]:
##RANDOM
np.random.randn(4)



array([-1.18803736, -0.81079014, -0.09121313, -1.2802774 ])

In [ ]:
np.random.randn(4,4)

array([[-1.91601803, -0.26809112,  0.13332419,  0.48504323],
       [ 0.1994926 , -0.07449853,  0.79933394, -0.52205405],
       [ 0.39536565,  0.35165552,  2.05648018, -2.1720355 ],
       [-0.48769448,  0.73345453,  2.28823803,  1.21542872]])

In [ ]:
np.random.randint(6)

3

In [ ]:
np.random.randint(6,300,5)

array([ 48, 284,  94, 299,   9])

In [ ]:
##NUMPY METHODS
benimDizi= np.arange(30)
benimDizi.reshape(5,6)        ## diziyi matrise çevirme


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
benimDizi.reshape(2,3,5)     ## diziyi tensöre çevirme

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [ ]:
benimDizi.max()

29

In [ ]:
benimDizi.argmax() ## Kaçıncı dizede olduğunu verir

29

# SLICING in NUMPY ARRAY

In [ ]:
dizi = np.arange(0,15)
dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
dizi[3:8] = -5    ## 3. index  7. index arasındaki elemanları değiştirmek için kullanlır.
dizi

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
dizi[:] = 100 ## HEPSİNİ 100 YAPAR for döngüsü
dizi

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100])

In [ ]:
diziKopyası = dizi.copy() ## dizinin kopyasını alır bunu yapmassak , başka bir değişkeni diziye eşitlediğimizde ve o değişkeni kullandığımızda ana dizimizde değişir

# MATRİX

In [ ]:
benimListem = [[10,20,30],[40,60,50],[60,70,80]]
benimListem


[[10, 20, 30], [40, 60, 50], [60, 70, 80]]

In [ ]:
matrix = np.array(benimListem)
matrix

array([[10, 20, 30],
       [40, 60, 50],
       [60, 70, 80]])

In [ ]:
matrix[1:,2]

array([50, 80])

In [ ]:
matrix[:2,2]

array([30, 50])

In [ ]:
matrix [[0,1]] ## 0 ve 1. satırı getirir

array([[10, 20, 30],
       [40, 60, 50]])

# OPERASYONLAR

In [ ]:
randomDizi= np.random.randint(1,100,20)
randomDizi

In [ ]:
randomDizi > 24

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True])

In [ ]:
sonucDizi = randomDizi > 24
sonucDizi

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True])

In [ ]:
randomDizi[sonucDizi]
randomDizi

array([46, 73, 80, 72, 33, 75, 71, 17, 37, 66, 70, 55, 88, 40, 78, 27,  2,
       18, 30, 96])

In [ ]:
np.sqrt(randomDizi)

array([6.78232998, 8.54400375, 8.94427191, 8.48528137, 5.74456265,
       8.66025404, 8.42614977, 4.12310563, 6.08276253, 8.1240384 ,
       8.36660027, 7.41619849, 9.38083152, 6.32455532, 8.83176087,
       5.19615242, 1.41421356, 4.24264069, 5.47722558, 9.79795897])